import type {
  SiteEditorSettings,
  SitePage,
} from "./theme-types";

export const sampleSitePages: SitePage[] = [
  { id: "page-1", type: "home", title: "Home", path: "/", enabled: true },
  { id: "page-2", type: "products", title: "Shop", path: "/shop", enabled: true },
  { id: "page-3", type: "categories", title: "Categories", path: "/categories", enabled: true },
  { id: "page-4", type: "cart", title: "Cart", path: "/cart", enabled: true },
  { id: "page-5", type: "checkout", title: "Checkout", path: "/checkout", enabled: true },
  { id: "page-6", type: "about", title: "About", path: "/about", enabled: true },
  { id: "page-7", type: "contact", title: "Contact", path: "/contact", enabled: true },
  { id: "page-8", type: "faq", title: "FAQ", path: "/faq", enabled: true },
  { id: "page-9", type: "privacy", title: "Privacy Policy", path: "/privacy", enabled: true },
  { id: "page-10", type: "terms", title: "Terms", path: "/terms", enabled: true },
  { id: "page-11", type: "productDetail", title: "Product", path: "/shop/:slug", enabled: true },
  { id: "page-12", type: "notFound", title: "Page Not Found", path: "/404", enabled: true },
];

export const defaultSettings: SiteEditorSettings = {
  siteName: "Bazaar",
  logoType: "text",
  logoImage: "",
  tagline: "",
  primaryColor: "#2563EB",
  accentColor: "#0F172A",
  surfaceColor: "#F8FAFC",
  displayFont: "outfit",
  bodyFont: "inter",
  buttonStyle: "Rounded",
  // Curated page links only
  navLinks: [
    { id: "nav-1", label: "Home", path: "/" },
    { id: "nav-2", label: "Shop", path: "/shop" },
    { id: "nav-3", label: "Best Sellers", path: "/shop?filter=featured" },
    { id: "nav-4", label: "New Arrivals", path: "/shop?sort=new" },
    { id: "nav-5", label: "Deals", path: "/shop?filter=featured" },
    { id: "nav-6", label: "Track Order", path: "/faq" },
    { id: "nav-7", label: "Customer Support", path: "/contact" },
  ],
  headerButtons: [],
  pages: sampleSitePages,
  // Marketplace home order with all section types included by default for skeleton rendering
  sections: [
    { id: "sec-1", type: "hero" },
    { id: "sec-2", type: "features" },
    { id: "sec-3", type: "categories" },
    { id: "sec-4", type: "featureProducts" },
    { id: "sec-5", type: "productShowcase" },
    { id: "sec-6", type: "categoryShowcase" },
    { id: "sec-7", type: "whyChooseUs" },
    { id: "sec-8", type: "testimonials" },
    { id: "sec-9", type: "banner" },
    { id: "sec-10", type: "footer" },
  ],
  announcementItems: [],
  announcementDivider: "·",
  heroImages: [],
  heroImagesSquare: [],
  selectedEventIds: [],
  categoriesTitle: "Shop by Category",
  selectedCategoryIds: [],
  featureProductsTitle: "Best Sellers",
  selectedProductIds: [],
  showcaseProductId: "",
  whyTitle: "Why shop with us",
  whyImage: "",
  why1Title: "",
  why1: "",
  why2Title: "",
  why2: "",
  why3Title: "",
  why3: "",
  categoryShowcaseTitle: "Popular categories",
  categoryShowcaseCategoryIds: [],
  featuresTitle: "Why customers trust us",
  feature1Title: "",
  feature1: "",
  feature1IconKind: "icon",
  feature1Icon: "package",
  feature1Image: "",
  feature2Title: "",
  feature2: "",
  feature2IconKind: "icon",
  feature2Icon: "tag",
  feature2Image: "",
  feature3Title: "",
  feature3: "",
  feature3IconKind: "icon",
  feature3Icon: "truck",
  feature3Image: "",
  testimonialsTitle: "",
  testimonials: [],
  ctaTitle: "",
  ctaBody: "",
  ctaButton: "",
  footerDescription: "",
  footerShopLabel: "Shop",
  footerShopLinks: [
    { id: "fs1", label: "All products", path: "/shop" },
    { id: "fs2", label: "Featured", path: "/shop?filter=featured" },
    { id: "fs3", label: "New arrivals", path: "/shop?sort=new" },
    { id: "fs4", label: "Categories", path: "/categories" },
  ],
  footerCompanyLabel: "Company",
  footerCompanyLinks: [
    { id: "fc1", label: "About", path: "/about" },
    { id: "fc2", label: "Contact", path: "/contact" },
    { id: "fc3", label: "FAQ", path: "/faq" },
    { id: "fc4", label: "Privacy", path: "/privacy" },
    { id: "fc5", label: "Terms", path: "/terms" },
  ],
};
