import type {
  Product,
  ProductCategory,
  SiteEditorSettings,
  SitePage,
} from "./theme-types";

/** Unsplash demo art — remote URLs only, never local asset imports. */
const img = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const sampleCategories: ProductCategory[] = [
  {
    id: "cat-electronics",
    slug: "electronics",
    name: "Electronics",
    description: "Gadgets, gadgets, and more gadgets for every desk.",
    image: img("photo-1498049794561-7780e7231661", 600),
    banner: img("photo-1498049794561-7780e7231661", 1400),
    icon: "cpu",
    itemCount: 48,
    featured: true,
  },
  {
    id: "cat-fashion",
    slug: "fashion",
    name: "Fashion",
    description: "Everyday wear for work, weekends, and everything between.",
    image: img("photo-1445205170230-053b83016050", 600),
    banner: img("photo-1445205170230-053b83016050", 1400),
    icon: "shirt",
    itemCount: 120,
    featured: true,
  },
  {
    id: "cat-home",
    slug: "home-living",
    name: "Home & Living",
    description: "Furniture, kitchenware, and comfort for every room.",
    image: img("photo-1616486338812-3dadae4b4ace", 600),
    banner: img("photo-1616486338812-3dadae4b4ace", 1400),
    icon: "home",
    itemCount: 86,
    featured: true,
  },
  {
    id: "cat-beauty",
    slug: "beauty",
    name: "Beauty & Personal Care",
    description: "Skincare, haircare, and grooming essentials.",
    image: img("photo-1596462502278-27bfdc403348", 600),
    banner: img("photo-1596462502278-27bfdc403348", 1400),
    icon: "sparkles",
    itemCount: 64,
    featured: true,
  },
  {
    id: "cat-mobile",
    slug: "mobile-accessories",
    name: "Mobile & Accessories",
    description: "Phones, cases, chargers, and audio.",
    image: img("photo-1511707171634-5f897ff02aa9", 600),
    banner: img("photo-1511707171634-5f897ff02aa9", 1400),
    icon: "smartphone",
    itemCount: 92,
    featured: true,
  },
  {
    id: "cat-appliances",
    slug: "appliances",
    name: "Appliances",
    description: "Kitchen and home appliances that actually last.",
    image: img("photo-1556911220-bff31c812dba", 600),
    banner: img("photo-1556911220-bff31c812dba", 1400),
    icon: "plug",
    itemCount: 41,
    featured: true,
  },
  {
    id: "cat-kids",
    slug: "toys-kids-baby",
    name: "Toys, Kids & Baby",
    description: "Toys, gear, and essentials for little ones.",
    image: img("photo-1515488042361-ee00e0ddd4e4", 600),
    banner: img("photo-1515488042361-ee00e0ddd4e4", 1400),
    icon: "baby",
    itemCount: 55,
    featured: false,
  },
  {
    id: "cat-sports",
    slug: "sports-outdoors",
    name: "Sports & Outdoors",
    description: "Gear for the gym, pitch, and trail.",
    image: img("photo-1461896836934-ffe607ba6851", 600),
    banner: img("photo-1461896836934-ffe607ba6851", 1400),
    icon: "dumbbell",
    itemCount: 38,
    featured: true,
  },
  {
    id: "cat-books",
    slug: "books-stationery",
    name: "Books & Stationery",
    description: "Reads, notebooks, and desk supplies.",
    image: img("photo-1495446815901-a7297e633e8d", 600),
    banner: img("photo-1495446815901-a7297e633e8d", 1400),
    icon: "book-open",
    itemCount: 70,
    featured: false,
  },
  {
    id: "cat-auto",
    slug: "automotive",
    name: "Automotive",
    description: "Car care, accessories, and tools.",
    image: img("photo-1492144534655-ae79c964c9d7", 600),
    banner: img("photo-1492144534655-ae79c964c9d7", 1400),
    icon: "car",
    itemCount: 29,
    featured: false,
  },
];

const deliveryAreas = [
  { name: "Inside Dhaka", charge: 80 },
  { name: "Outside Dhaka", charge: 150 },
];

const defaultProductFeatures = [
  {
    title: "Quality checked",
    description: "Inspected before shipping so you receive what you ordered.",
  },
  {
    title: "Easy returns",
    description: "Hassle-free returns on eligible items within the return window.",
  },
  {
    title: "Secure checkout",
    description: "COD and protected payment options on every order.",
  },
];

function product(
  partial: Omit<Product, "freeDelivery" | "deliveryCharges" | "inStock" | "stockCount"> &
    Partial<Pick<Product, "freeDelivery" | "deliveryCharges" | "inStock" | "stockCount" | "features">>,
): Product {
  return {
    freeDelivery: false,
    deliveryCharges: deliveryAreas,
    inStock: true,
    stockCount: 40,
    features: defaultProductFeatures,
    ...partial,
  };
}

export const sampleProducts: Product[] = [
  product({
    id: "prod-1",
    slug: "wireless-earbuds-pro",
    name: "Wireless Earbuds Pro",
    tagline: "Noise-cancelling true wireless earbuds",
    description: "Clear sound, long battery life, and a secure fit for all-day wear.",
    longDescription:
      "Active noise cancellation, 28-hour total playtime with the case, IPX4 water resistance, and touch controls. Ships with three ear-tip sizes.",
    price: 3490,
    originalPrice: 4990,
    discountPercent: 30,
    images: [img("photo-1590658268037-6bf12165a8df"), img("photo-1606220945770-b5b6c2c55bf1")],
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    rating: 4.6,
    reviewCount: 1284,
    badge: "Bestseller",
    featured: true,
    features: [
      { title: "Active noise cancel", description: "Blocks ambient noise for clear calls and focus." },
      { title: "28-hour battery", description: "All-day buds plus case charging on the go." },
      { title: "IPX4 water resist", description: "Sweat and splash ready for workouts." },
    ],
  }),
  product({
    id: "prod-2",
    slug: "cotton-oversized-tee",
    name: "Cotton Oversized Tee",
    tagline: "Heavyweight everyday cotton tee",
    description: "Soft mid-weight cotton with a relaxed oversized cut.",
    price: 890,
    originalPrice: 1290,
    discountPercent: 31,
    images: [img("photo-1521572163474-6864f9cf17ab"), img("photo-1583743814966-8936f5b7be1a")],
    categoryId: "cat-fashion",
    categoryName: "Fashion",
    rating: 4.4,
    reviewCount: 562,
    featured: true,
    sizes: ["S", "M", "L", "XL"],
  }),
  product({
    id: "prod-3",
    slug: "ceramic-table-lamp",
    name: "Ceramic Table Lamp",
    tagline: "Warm ambient light for desks and nightstands",
    description: "Matte ceramic base with a linen shade. E27 bulb not included.",
    price: 2450,
    originalPrice: 3200,
    discountPercent: 23,
    images: [img("photo-1507473885765-e6ed057f782c"), img("photo-1513506003901-1e6a229e2d15")],
    categoryId: "cat-home",
    categoryName: "Home & Living",
    rating: 4.7,
    reviewCount: 219,
    featured: true,
  }),
  product({
    id: "prod-4",
    slug: "vitamin-c-serum",
    name: "Vitamin C Brightening Serum",
    tagline: "Daily glow serum for dull skin",
    description: "Lightweight serum with vitamin C and hyaluronic acid.",
    price: 1290,
    originalPrice: 1690,
    discountPercent: 24,
    images: [img("photo-1620916564521-7093f28c8c13"), img("photo-1570194065650-d99fb4b38b17")],
    categoryId: "cat-beauty",
    categoryName: "Beauty & Personal Care",
    rating: 4.5,
    reviewCount: 891,
    featured: true,
  }),
  product({
    id: "prod-5",
    slug: "magnetic-phone-case",
    name: "MagSafe Compatible Case",
    tagline: "Slim case with built-in magnet ring",
    description: "Drop-tested shell that works with MagSafe chargers and wallets.",
    price: 790,
    originalPrice: 1100,
    discountPercent: 28,
    images: [img("photo-1601784551446-20c9e07cdbdb"), img("photo-1592890288564-76628a30a657")],
    categoryId: "cat-mobile",
    categoryName: "Mobile & Accessories",
    rating: 4.3,
    reviewCount: 445,
    featured: true,
  }),
  product({
    id: "prod-6",
    slug: "air-fryer-5l",
    name: "5L Digital Air Fryer",
    tagline: "Crispy results with less oil",
    description: "Eight presets, digital display, and non-stick basket for everyday cooking.",
    price: 6990,
    originalPrice: 8990,
    discountPercent: 22,
    images: [img("photo-1585515320310-259814833e62"), img("photo-1556910103-1c02745aae4d")],
    categoryId: "cat-appliances",
    categoryName: "Appliances",
    rating: 4.8,
    reviewCount: 672,
    badge: "Hot deal",
    featured: true,
  }),
  product({
    id: "prod-7",
    slug: "wooden-building-blocks",
    name: "Wooden Building Blocks Set",
    tagline: "100-piece natural wood set",
    description: "Smooth, unfinished hardwood blocks for creative play ages 3+.",
    price: 1590,
    originalPrice: 1990,
    discountPercent: 20,
    images: [img("photo-1515488042361-ee00e0ddd4e4"), img("photo-1566576912321-d58ddd7a6088")],
    categoryId: "cat-kids",
    categoryName: "Toys, Kids & Baby",
    rating: 4.9,
    reviewCount: 310,
    featured: false,
  }),
  product({
    id: "prod-8",
    slug: "yoga-mat-pro",
    name: "Pro Grip Yoga Mat",
    tagline: "6mm cushion with non-slip surface",
    description: "Closed-cell foam mat that grips wet or dry. Includes carry strap.",
    price: 1890,
    originalPrice: 2490,
    discountPercent: 24,
    images: [img("photo-1601925260368-ae2f83cf8b7f"), img("photo-1544367567-0f2fcb009e0b")],
    categoryId: "cat-sports",
    categoryName: "Sports & Outdoors",
    rating: 4.6,
    reviewCount: 503,
    featured: true,
  }),
  product({
    id: "prod-9",
    slug: "lined-notebook-a5",
    name: "A5 Lined Notebook",
    tagline: "Hardcover 160-page journal",
    description: "Cream paper, elastic band, and ribbon bookmark. Ideal for daily notes.",
    price: 450,
    originalPrice: 650,
    discountPercent: 31,
    images: [img("photo-1531346878377-a5be20888e57"), img("photo-1544716278-ca5e3f4abd8c")],
    categoryId: "cat-books",
    categoryName: "Books & Stationery",
    rating: 4.4,
    reviewCount: 188,
    freeDelivery: true,
    deliveryCharges: [],
    featured: false,
  }),
  product({
    id: "prod-10",
    slug: "car-phone-mount",
    name: "Dashboard Phone Mount",
    tagline: "One-hand adjustable car mount",
    description: "Strong suction base with 360° ball joint. Fits most smartphones.",
    price: 690,
    originalPrice: 990,
    discountPercent: 30,
    images: [img("photo-1486262715619-67b85e0b08d3"), img("photo-1449965408869-eaa3f722e40d")],
    categoryId: "cat-auto",
    categoryName: "Automotive",
    rating: 4.2,
    reviewCount: 256,
    featured: false,
  }),
  product({
    id: "prod-11",
    slug: "smart-watch-lite",
    name: "Smart Watch Lite",
    tagline: "Fitness tracking without the bulk",
    description: "Heart-rate, sleep, and 14-day battery. Water-resistant to 5 ATM.",
    price: 4290,
    originalPrice: 5990,
    discountPercent: 28,
    images: [img("photo-1523275335684-37898b6baf30"), img("photo-1579586337278-3befd40fd17a")],
    categoryId: "cat-electronics",
    categoryName: "Electronics",
    rating: 4.5,
    reviewCount: 974,
    badge: "New",
    featured: true,
  }),
  product({
    id: "prod-12",
    slug: "linen-throw-blanket",
    name: "Linen Throw Blanket",
    tagline: "Breathable year-round throw",
    description: "Stonewashed linen, 130×180 cm. Softens with every wash.",
    price: 2890,
    originalPrice: 3600,
    discountPercent: 20,
    images: [img("photo-1584100936595-c0654b55a2e2"), img("photo-1631679706909-1844bbd07221")],
    categoryId: "cat-home",
    categoryName: "Home & Living",
    rating: 4.7,
    reviewCount: 141,
    featured: true,
  }),
];

export const sampleSitePages: SitePage[] = [
  { id: "page-1", type: "home", title: "Home", path: "/", enabled: true },
  { id: "page-2", type: "products", title: "Shop", path: "/shop", enabled: true },
  { id: "page-3", type: "categories", title: "Categories", path: "/categories", enabled: true },
  { id: "page-4", type: "cart", title: "Cart", path: "/cart", enabled: true },
  { id: "page-5", type: "checkout", title: "Checkout", path: "/checkout", enabled: true },
  { id: "page-6", type: "about", title: "About", path: "/about", enabled: true },
  { id: "page-7", type: "contact", title: "Contact", path: "/contact", enabled: true },
  { id: "page-8", type: "faq", title: "FAQ", path: "/faq", enabled: true },
  { id: "page-9", type: "privacy", title: "Privacy Policy", path: "/privacy", enabled: true },
  { id: "page-10", type: "terms", title: "Terms", path: "/terms", enabled: true },
  { id: "page-11", type: "productDetail", title: "Product", path: "/shop/:slug", enabled: true },
  { id: "page-12", type: "notFound", title: "Page Not Found", path: "/404", enabled: true },
];

export const defaultSettings: SiteEditorSettings = {
  siteName: "Bazaar",
  logoType: "text",
  logoImage: "",
  tagline: "Everything you need, delivered",
  primaryColor: "#2563EB",
  accentColor: "#0F172A",
  surfaceColor: "#F8FAFC",
  displayFont: "outfit",
  bodyFont: "inter",
  buttonStyle: "Rounded",
  // Curated page links only — full category list lives in the All Categories
  // dropdown / hero rail, not as a second nav row of every department name.
  navLinks: [
    { id: "nav-1", label: "Home", path: "/" },
    { id: "nav-2", label: "Shop", path: "/shop" },
    { id: "nav-3", label: "Best Sellers", path: "/shop?filter=featured" },
    { id: "nav-4", label: "New Arrivals", path: "/shop?sort=new" },
    { id: "nav-5", label: "Deals", path: "/shop?filter=featured" },
    { id: "nav-6", label: "Track Order", path: "/faq" },
    { id: "nav-7", label: "Customer Support", path: "/contact" },
  ],
  headerButtons: [],
  pages: sampleSitePages,
  // Marketplace home order: trust strip sits directly under the hero, then
  // catalog (categories → best sellers). No testimonials / banner CTA / showcase.
  sections: [
    { id: "sec-1", type: "hero" },
    { id: "sec-2", type: "features" }, // trust badges — must stay right under hero
    { id: "sec-3", type: "categories" },
    { id: "sec-4", type: "featureProducts" },
    { id: "sec-5", type: "whyChooseUs" },
    { id: "sec-6", type: "footer" },
  ],
  announcementItems: ["Free delivery over ৳2,500", "COD available nationwide", "Easy 7-day returns"],
  announcementDivider: "·",
  heroImages: [
    img("photo-1607082348824-0a96f2a4b9da", 1600),
    img("photo-1556742049-0cfed4f6a45d", 1600),
    img("photo-1472851294608-062f824d29cc", 1600),
  ],
  heroImagesSquare: [img("photo-1607082348824-0a96f2a4b9da", 900)],
  categoriesTitle: "Shop by Category",
  selectedCategoryIds: sampleCategories.map((c) => c.id),
  featureProductsTitle: "Best Sellers",
  selectedProductIds: [
    "prod-1",
    "prod-6",
    "prod-11",
    "prod-2",
    "prod-4",
    "prod-8",
    "prod-3",
    "prod-5",
  ],
  showcaseProductId: "prod-1",
  whyTitle: "Why shop with us",
  whyImage: img("photo-1556740758-90de374c12ad", 1000),
  why1Title: "Curated catalog",
  why1: "Thousands of products across everyday categories — filtered, priced, and ready to ship.",
  why2Title: "Transparent pricing",
  why2: "Clear delivery charges by area, no surprise fees at checkout.",
  why3Title: "Buyer protection",
  why3: "COD, secure payments, and hassle-free returns when something isn't right.",
  categoryShowcaseTitle: "Popular departments",
  categoryShowcaseCategoryIds: [
    "cat-electronics",
    "cat-fashion",
    "cat-home",
    "cat-mobile",
  ],
  featuresTitle: "Why customers trust us",
  feature1Title: "Wide Range",
  feature1: "Millions of products across categories — find what you need in one place.",
  feature1IconKind: "icon",
  feature1Icon: "package",
  feature1Image: "",
  feature2Title: "Best Prices",
  feature2: "Unbeatable deals and everyday low prices with clear discount labels.",
  feature2IconKind: "icon",
  feature2Icon: "tag",
  feature2Image: "",
  feature3Title: "Fast Delivery",
  feature3: "Reliable delivery across Bangladesh with area-based shipping rates.",
  feature3IconKind: "icon",
  feature3Icon: "truck",
  feature3Image: "",
  testimonialsTitle: "",
  testimonials: [],
  ctaTitle: "",
  ctaBody: "",
  ctaButton: "",
  footerDescription:
    "Bazaar is a multi-category marketplace for everyday essentials — electronics, fashion, home, and more. Built for merchants who sell everything.",
  footerShopLabel: "Shop",
  footerShopLinks: [
    { id: "fs1", label: "All products", path: "/shop" },
    { id: "fs2", label: "Featured", path: "/shop?filter=featured" },
    { id: "fs3", label: "New arrivals", path: "/shop?sort=new" },
    { id: "fs4", label: "Categories", path: "/categories" },
  ],
  footerCompanyLabel: "Company",
  footerCompanyLinks: [
    { id: "fc1", label: "About", path: "/about" },
    { id: "fc2", label: "Contact", path: "/contact" },
    { id: "fc3", label: "FAQ", path: "/faq" },
    { id: "fc4", label: "Privacy", path: "/privacy" },
    { id: "fc5", label: "Terms", path: "/terms" },
  ],
};

/** Trust-badge strip on the home page — mirrors the features section fields
 * plus two fixed extras so the strip always has the classic 5-item marketplace layout. */
export const trustBadges = [
  { titleKey: "feature1Title" as const, bodyKey: "feature1" as const, icon: "grid" as const },
  { titleKey: "feature2Title" as const, bodyKey: "feature2" as const, icon: "tag" as const },
  { titleKey: "feature3Title" as const, bodyKey: "feature3" as const, icon: "truck" as const },
  {
    title: "Secure Payment",
    body: "100% safe & secure checkout — COD and trusted gateways.",
    icon: "shield" as const,
  },
  {
    title: "Easy Returns",
    body: "Hassle-free returns within 7 days on eligible items.",
    icon: "refresh" as const,
  },
];
